<?php
/**
 * @file
 * Code for the StoriedMaps Core feature.
 */

include_once 'storiedmaps_core.features.inc';

/**
 * Implements hook_modules_installed().
 *
 * Unset distracting messages at install time.
 */
function storiedmaps_core_modules_enabled($modules) {
  if (drupal_installation_attempted() && in_array('storiedmaps_core', $modules)) {
    drupal_get_messages('status');
    drupal_get_messages('warning');
  }
}

/**
 * Implements hook_context_load_alter().
 *
 * Move the loging block to the footer region.
 */
function storiedmaps_core_context_load_alter(&$context) {
  if ($context->name === 'comment-login' && isset($context->reactions['block'])) {
    $context->reactions['block']['blocks']['user-login']['region'] = 'footer';
    $context->reactions['block']['blocks']['logintoboggan-logintoboggan_logged_in']['region'] = 'footer';
  }
}

